### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lerixhe** [oliyg/juejinxiaoce#15]
===navagating to main page
===login...
===getting book section list
===getting book HTML content
开篇词 —— 小册食用指南
===writing html...
===getting book HTML content
===write html file success
===writing markdown...
===write markdown file success
(node:15252) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at mkdir (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\utils.js:7:26)
    at Juejin.copyToPWDDir (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\app.js:26:5)
    at juejin.getContentHTML (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\app.js:196:14)       
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TCP/IP 历史与分层模型
===writing html...
===getting book HTML content
===write html file success
===writing markdown...
===write markdown file success
(node:15252) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at mkdir (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\utils.js:7:26)
    at Juejin.copyToPWDDir (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\app.js:26:5)
    at juejin.getContentHTML (C:\Users\Lerix\AppData\Roaming\npm\node_modules\@oliyg\juejinxiaoce\app.js:196:14)       
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by ljjbluesky** [comment]
我也是，怎么解决呢？

**Comment by Lancelothe** [comment]
UnhandledPromiseRejectionWarning
这是没购买导致的吧，这个项目难道不是破解的，只是纯导出的？

**Comment by nekolr** [comment]
我也遇到了这个情况，小册是购买过的，只是导出也报这个

**Comment by lerixhe** [comment]
各位，这是我很久提的issue,你们用得是windows吧，后来我用WSL就不报错了。所以就没有深究，你们可以试试 @nekolr @ljjbluesky @Lancelothe

**Comment by nekolr** [comment]
> 
> 
> 各位，这是我很久提的issue,你们用得是windows吧，后来我用WSL就不报错了。所以就没有深究，你们可以试试 @nekolr @ljjbluesky @Lancelothe

感谢，回头试试

**Comment by tangyiming** [comment]
使用git bash运行也没问题 bash可能有乱码 导出文件没问题
