### ISSUE TITLE
规则改了吗，bookid输入后报错

### ISSUE THREAD

**Issue by DeJoker** [oliyg/juejinxiaoce#21]

**Comment by DeJoker** [comment]
===navagating to main page
TypeError: Cannot read property 'map' of undefined
    at getCookieObj (/usr/local/lib/node_modules/@oliyg/juejinxiaoce/utils.js:78:27)
    at Juejin.mainPage (/usr/local/lib/node_modules/@oliyg/juejinxiaoce/app.js:69:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

![image](https://user-images.githubusercontent.com/18501966/91817344-d9516c00-ec67-11ea-99ae-02b001cd31cc.png)

**Comment by redbearder** [comment]
> ===navagating to main page
> TypeError: Cannot read property 'map' of undefined
> at getCookieObj (/usr/local/lib/node_modules/@oliyg/juejinxiaoce/utils.js:78:27)
> at Juejin.mainPage (/usr/local/lib/node_modules/@oliyg/juejinxiaoce/app.js:69:34)
> at
> at process._tickCallback (internal/process/next_tick.js:188:7)
> 
> ![image](https://user-images.githubusercontent.com/18501966/91817344-d9516c00-ec67-11ea-99ae-02b001cd31cc.png)

我也是冲着这本书来的。。。。。。

**Comment by The-Dark-Forest** [comment]
一样的错误，看来是规则改了

**Comment by brightzoe** [comment]
same as me.
已经不能用了
